In [1]:
import networkx as nx
import numpy as np

In [12]:
# create preferential attachment graph
G = nx.barabasi_albert_graph(1000, 2)


In [15]:
A = nx.adjacency_matrix(G).todense()
A

array([[0, 1, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [11]:
# compute page rank
pr = nx.pagerank(G, alpha=0.85)
list(pr.values())[0:10]


[0.019057182893168052,
 0.009962285367912346,
 0.0012134151756254014,
 0.004290459228036947,
 0.013267302576801263,
 0.004099457443595425,
 0.004797073018052519,
 0.011903864992017704,
 0.00540868681528103,
 0.000976889765678717]

In [66]:
def get_H(A):
    m,_ = A.shape
    H = np.zeros_like(A).astype(float)
    for i in range(m):
        out_degree = np.sum(A[i,:])
        for j in range(m):
            if A[i,j] == 1:
                H[i][j] = 1.0/out_degree
    return H
def get_Sink(A):
    m,_ = A.shape
    S = np.zeros_like(A).astype(float)
    for i in range(m):
        in_degree = np.sum(A[:,i])
        if in_degree == 0:
            S[:,i] = 1/m
    return S
def page_rank(G,alpha=0.85,p=None,num_iter=100):
    A = nx.adjacency_matrix(G).todense()
    H = get_H(A)
    S = H+get_Sink(A)
    if p is None:
        p = np.ones(A.shape[0])/A.shape[0]
    r = np.random.rand(A.shape[0])
    for _ in range(num_iter):
        r = alpha * (S.T @ r) + (1-alpha)*p
    return r,A,H,S,p
        


In [92]:
r,A,H,S,p = page_rank(G,num_iter=1000)

In [94]:
# take the 10 highest ranked nodes
np.argsort(r)[-10:]

array([27, 63,  7, 31, 13,  6,  9, 22,  8,  0])

In [96]:
pr = nx.pagerank(G, alpha=0.85)
# get the 10 highest ranked nodes
np.argsort(list(pr.values()))[-10:]


array([27, 63,  7, 31, 13,  6,  9, 22,  8,  0])

8010677102

In [ ]:
import numpy as np
def polar(x,A):
    return (x.T @ A @ x)/(x.T @ x)
def 

collegs = [(0,1,1),(0,2,1),(1,3,1),(2,3,-1),(2,4,-1),(3,4,1)]
